import { Injectable } from '@nestjs/common';
import { execFile } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { promisify } from 'node:util';
import { PurfenceProject } from './purfence-project.entity';
import { ensureDir, writeText } from '../common/utils/file.util';
import { PurfenceConfigService } from './purfence-config/purfence-config.service';

const execFileAsync = promisify(execFile);

@Injectable()
export class PurfenceProjectService {
  constructor(private readonly purfenceConfigService: PurfenceConfigService) {}

  async initProjectFilesystem(projectId: string) {
    const project = await PurfenceProject.findOne({ where: { id: projectId } });
    if (!project) {
      throw new Error(`Project not found: ${projectId}`);
    }

    if (project.localRootPath) {
      return project;
    }

    if (!project.slug) {
      throw new Error('Project slug is required');
    }

    const projectsRoot = await this.purfenceConfigService.getProjectsRootPathOrThrow();
    const projectRootPath = path.join(projectsRoot, project.slug);

    const worktreesPath = path.join(projectRootPath, 'worktrees');
    const attachmentsPath = path.join(projectRootPath, 'attachments');

    await ensureDir(worktreesPath);
    await ensureDir(attachmentsPath);

    let repoPath: string;

    if (project.externalPath) {
      repoPath = await this.setupImportedRepo(projectRootPath, project.externalPath);
    } else {
      repoPath = path.join(projectRootPath, 'repo');
      await ensureDir(repoPath);
    }

    // 检查是否需要 git init
    if (!fs.existsSync(path.join(repoPath, '.git'))) {
      await execFileAsync('git', ['init', '-b', project.defaultBranch], { cwd: repoPath });
    }

    // 检测实际的主分支名称（导入的项目可能是 master 或 main）
    if (!project.defaultBranch || project.defaultBranch === 'main') {
      try {
        const { stdout } = await execFileAsync('git', ['branch', '--show-current'], { cwd: repoPath });
        const currentBranch = stdout.trim();
        if (currentBranch && currentBranch !== 'main') {
          project.defaultBranch = currentBranch;
        }
      } catch {
        // 忽略错误，使用默认的 main
      }
    }

    // 创建 .purfence 目录结构（在 repo 路径下）
    const projectPurfenceDir = path.join(repoPath, '.purfence');
    const dirs = [
      projectPurfenceDir,
      path.join(projectPurfenceDir, 'inputs'),
      path.join(projectPurfenceDir, 'artifacts'),
      path.join(projectPurfenceDir, 'meta'),
      path.join(projectPurfenceDir, 'attachments'),
    ];
    for (const dir of dirs) {
      await ensureDir(dir);
    }

    // 写入 .purfence/README.md（如果不存在）
    const readmePath = path.join(projectPurfenceDir, 'README.md');
    if (!fs.existsSync(readmePath)) {
      await writeText(
        readmePath,
        '# .purfence\n\nGenerated by purfence.\n',
      );
    }

    // 创建 .gitkeep 文件保持空目录（如果不存在）
    const gitkeepFiles = [
      path.join(projectPurfenceDir, 'inputs', '.gitkeep'),
      path.join(projectPurfenceDir, 'artifacts', '.gitkeep'),
      path.join(projectPurfenceDir, 'meta', '.gitkeep'),
      path.join(projectPurfenceDir, 'attachments', '.gitkeep'),
    ];
    for (const gitkeep of gitkeepFiles) {
      if (!fs.existsSync(gitkeep)) {
        await writeText(gitkeep, '');
      }
    }

    // 只有创建模式才执行 git add/commit
    if (!project.externalPath) {
      try {
        await execFileAsync('git', ['add', '.purfence'], { cwd: repoPath });
        await execFileAsync('git', ['commit', '-m', 'chore: init project'], { cwd: repoPath });
      } catch {
        throw new Error('Failed to create initial git commit. Please ensure git user.name/user.email are configured.');
      }
    }

    project.localRootPath = projectRootPath;
    await project.save();

    return project;
  }

  private async setupImportedRepo(projectRootPath: string, externalPath: string): Promise<string> {
    // 验证外部路径是否存在
    if (!fs.existsSync(externalPath)) {
      throw new Error(`External path does not exist: ${externalPath}`);
    }

    const stats = fs.statSync(externalPath);
    if (!stats.isDirectory()) {
      throw new Error(`External path is not a directory: ${externalPath}`);
    }

    // 创建软连接
    const repoLinkPath = path.join(projectRootPath, 'repo');
    try {
      fs.symlinkSync(externalPath, repoLinkPath);
    } catch (error) {
      // 如果错误与 ~ 符号相关，提供更详细的提示
      if (externalPath.includes('~')) {
        const suggestedPath = externalPath
          .replace('~/', '/Users/用户名/')
          .replace('~\\', 'C:\\Users\\用户名\\');

        throw new Error(
          `❌ 路径格式错误：不支持包含 ~ 的相对路径。

请使用绝对路径：
- macOS: /Users/用户名/${externalPath.replace('~/', '').replace('~\\', '')}
- Windows: C:\\Users\\用户名\\${externalPath.replace('~/', '').replace('~\\', '')}

原始错误：${error.message}`,
        );
      }
      throw new Error(`Failed to create symlink: ${error.message}`);
    }

    return repoLinkPath;
  }
}
